Repository suiranfes/sell.suiranfes.blue, pull requests merged in 2025-01, with the labels that each got.

#120 feat(gs-sheet): replace firebase to gs-sheet
  .gitignore
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/csvDownload.tsx
  src/dataFromFirebase.tsx
  src/dataToFirebase.tsx
  src/firebase.ts
  src/index.tsx
  src/localStorageLib.ts
  src/localToGSsheet.ts
  src/showCal.tsx
  src/user.css
  src/user.tsx
  vite.config.ts
Labels: enhancement

#127 style(ui): improved user interfaces
  src/App.tsx
  src/csvDownload.tsx
  src/showCal.tsx
  src/user.tsx
Labels: enhancement, good first issue

#128 feat: replace axios to fetch
  src/localToGSsheet.ts
  src/showCal.tsx
  src/user.tsx
Labels: bug, enhancement

#131 maybe done
  src/data.tsx
  src/index.tsx
Labels: enhancement
